// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Edit: typeof import('./src/components/Edit/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
